# Special Technique for handling both missing values for numerical and categorical data (Univariate)

## 1#Random Value Imputation 
## 2#Missing Imputer
## 3#Automatic Selection of parameter

## Random Imputation:

1. Preserves the variance of the variable (but why?)
2. Memory heavy for deployment, as we need to store the original training set to extract values from and replace the NA in coming observations.
3. Well suited for linear models as it does not distort the distribution, regardless of the % of NA

### Benefits of Random Imputation:

1. Easy to implement (can be used using only pandas not sklearn)
2. variance and distribution are intact

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/kaggle/input/datasets/shashikalarajesh11/titanic-dataset/Titanic-Dataset.csv',usecols=['Age','Fare','Survived'])

df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [3]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [4]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [6]:
x_train['Age_imputed']=x_train['Age']
x_test['Age_imputed']=x_train['Age']

In [7]:
x_train.head()

      Age     Fare  Age_imputed
30   40.0  27.7208         40.0
10    4.0  16.7000          4.0
873  47.0   9.0000         47.0
182   9.0  31.3875          9.0
876  20.0   9.8458         20.0

In [8]:
x_test.head()

      Age     Fare  Age_imputed
707  42.0  26.2875          NaN
37   21.0   8.0500          NaN
615  24.0  65.0000          NaN
169  28.0  56.4958          NaN
68   17.0   7.9250          NaN